  CREATE TABLE "PROMETHEAN"."PG_VC_DATA" 
   (	"ID_RECORD" NUMBER, 
	"OWNER" VARCHAR2(50 BYTE), 
	"OBJECT" VARCHAR2(50 BYTE), 
	"OBJ_TYPE" VARCHAR2(200 BYTE), 
	"DATE_VERSION" DATE, 
	"VERSION" NUMBER, 
	"CODE" CLOB, 
	"ID_CHECK_STAMP" NUMBER
   );
